[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
    "npm install",
    "npx prisma generate",
    "cd apps/api && npm install"
]

[phases.build]
cmds = ["cd apps/api && npm run build"]

[start]
cmd = "cd apps/api && npm start"
